# Generated by Django 4.2.14 on 2024-08-15 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramuser_is_teacher'),
        ('course', '0004_questionset_answered_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.questionset'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='answered_students',
            field=models.ManyToManyField(blank=True, related_name='answered_question_sets', to='bot.telegramuser'),
        ),
    ]
