# Generated by Django 4.2.14 on 2024-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramuser_is_teacher'),
        ('course', '0001_initial'),
        ('group', '0002_group_members_delete_groupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='finished_lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='bot.telegramuser'),
        ),
    ]
