# Generated by Django 4.2.14 on 2024-08-08 04:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads')),
                ('media_type', models.CharField(choices=[('file', 'File'), ('image', 'Image')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_all', models.BooleanField(default=False)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('media', models.ManyToManyField(blank=True, null=True, to='bot.media')),
                ('receivers', models.ManyToManyField(related_name='notifications', to='bot.telegramuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='promotion',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
