# Generated by Django 4.2.14 on 2024-08-08 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_media_notification_remove_photo_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='media',
        ),
        migrations.AddField(
            model_name='media',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.notification'),
        ),
    ]
