# Generated by Django 4.2.14 on 2024-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_notification_media_media_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
