# Generated by Django 5.0.7 on 2024-08-01 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot.social'),
        ),
    ]
