# Generated by Django 4.2.14 on 2024-08-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_requeststojoingroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
