# Generated by Django 4.2.14 on 2024-08-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentanswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
