END, GET_TASKS, GET_TASK, GET_TASK_ANSWER, QUESTION_SINGLE, QUESTION_NOTIFY, GET_ANSWER,  = range(-1, 6)
GET_RESULT_DETAILS, TEACHER_GET_LESSON_FOR_TASK, TEACHER_GET_TASK, TEACHER_GET_TASK_DETAILS = range(7, 11)
TEACHER_CONFIRM_TASK = range(11, 12)
